# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /apps
COPY . .

# Expose the Flask port
EXPOSE 5000

# Run the Flask application
CMD ["python", "main.py"]
